<?php


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $table = 'tasks';
    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'title',
        'description',
        'creator',
        'status',
        'start_date',
        'end_date',
    ];

    public function newEloquentBuilder($query)
    {
        return parent::newEloquentBuilder($query); // TODO: Change the autogenerated stub
    }

}
