version: "3"

services:

  php:
    build:
      context: .
      dockerfile: ./docker/images/php/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./laravel:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - retmix

  nginx:
    build:
      context: .
      dockerfile: ./docker/images/nginx/dev.Dockerfile
      args:
        NGINX_SERVER: ${NGINX_SERVER:-localhost}
    ports:
      - "${PORT_NGINX:-80}:80"
      - "${PORT_SSL:-443}:443"
    networks:
      - retmix

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-retmix}
      POSTGRES_USER: ${DB_USER:-retmix}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
    volumes:
      - dbData:/var/lib/postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - retmix

  adminer:
    image: adminer:4.8.1
    ports:
      - "${PORT_ADMINER:-8080}:8080"
    environment:
      - PMA_HOST=postgres
      - PMA_ABSOLUTE_URI=http://localhost:80/adminer
    depends_on:
      - postgres
    networks:
      - retmix

volumes:
  dbData:
    driver: local

networks:
  retmix:
    driver: bridge